# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pbf/Event.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'pbf/Event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpbf/Event.proto\x12\x06\x65vents\"\x85\x01\n\tEventSpec\x12\x11\n\teventUUID\x18\x01 \x01(\t\x12\x12\n\neventTitle\x18\x02 \x01(\t\x12\x18\n\x10\x65ventDescription\x18\x03 \x01(\t\x12\x11\n\teventHref\x18\x04 \x01(\t\x12\x11\n\teventTime\x18\x05 \x01(\t\x12\x11\n\timageHash\x18\x06 \x01(\t\".\n\tEventList\x12!\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x11.events.EventSpecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pbf.Event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTSPEC']._serialized_start=28
  _globals['_EVENTSPEC']._serialized_end=161
  _globals['_EVENTLIST']._serialized_start=163
  _globals['_EVENTLIST']._serialized_end=209
# @@protoc_insertion_point(module_scope)
